// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tunnel

import (
	"flux-panel-go/api/tunnel"
)

type ControllerV1 struct{}

func NewV1() tunnel.ITunnelV1 {
	return &ControllerV1{}
}
