// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package tunnel

// Tunnel type constants
const (
	TunnelTypePortForward   = 1 // 端口转发
	TunnelTypeTunnelForward = 2 // 隧道转发
)

// Tunnel status constants
const (
	TunnelStatusActive = 1 // 启用状态
)

// Node status constants
const (
	NodeStatusOnline = 1 // 节点在线状态
)

// User role constants
const (
	AdminRoleID = 0 // 管理员角色ID
)

// Success response messages
const (
	SuccessCreateMsg = "隧道创建成功"
	SuccessDeleteMsg = "隧道删除成功"
)

// Error response messages
const (
	ErrorCreateMsg           = "隧道创建失败"
	ErrorDeleteMsg           = "隧道删除失败"
	ErrorTunnelNotFound      = "隧道不存在"
	ErrorTunnelNameExists    = "隧道名称已存在"
	ErrorTunnelUpdateFailed  = "隧道更新失败"
	SuccessUpdateMsg         = "隧道更新成功"
	ErrorInNodeNotFound      = "入口节点不存在"
	ErrorOutNodeNotFound     = "出口节点不存在"
	ErrorOutNodeRequired     = "出口节点不能为空"
	ErrorOutPortRequired     = "出口端口不能为空"
	ErrorSameNodeNotAllowed  = "隧道转发模式下，入口和出口不能是同一个节点"
	ErrorInPortRangeInvalid  = "入口端口开始不能大于结束端口"
	ErrorOutPortRangeInvalid = "出口端口开始不能大于结束端口"
	ErrorNoAvailableTunnels  = "暂无可用隧道"
	ErrorInNodeOffline       = "入口节点当前离线，请确保节点正常运行"
	ErrorOutNodeOffline      = "出口节点当前离线，请确保节点正常运行"
)

// Usage check related messages
const (
	ErrorForwardsInUse        = "该隧道还有 %d 个转发在使用，请先删除相关转发"
	ErrorUserPermissionsInUse = "该隧道还有 %d 个用户权限关联，请先取消用户权限分配"
)
