// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package node

import (
	"flux-panel-go/api/node"
)

type ControllerV1 struct{}

func NewV1() node.INodeV1 {
	return &ControllerV1{}
}
