// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package node

const (
	// 节点默认状态：启用
	NODE_STATUS_ACTIVE = 0

	// 成功响应消息
	SUCCESS_CREATE_MSG = "节点创建成功"
	SUCCESS_UPDATE_MSG = "节点更新成功"
	SUCCESS_DELETE_MSG = "节点删除成功"

	// 错误响应消息
	ERROR_CREATE_MSG     = "节点创建失败"
	ERROR_UPDATE_MSG     = "节点更新失败"
	ERROR_DELETE_MSG     = "节点删除失败"
	ERROR_NODE_NOT_FOUND = "节点不存在"

	// 隧道使用检查相关消息
	ERROR_IN_NODE_IN_USE  = "该节点还有 %d 个隧道作为入口节点在使用，请先删除相关隧道"
	ERROR_OUT_NODE_IN_USE = "该节点还有 %d 个隧道作为出口节点在使用，请先删除相关隧道"

	// 端口范围验证相关消息
	ERROR_PORT_STA_REQUIRED  = "起始端口不能为空"
	ERROR_PORT_END_REQUIRED  = "结束端口不能为空"
	ERROR_PORT_RANGE_INVALID = "端口必须在1-65535范围内"
	ERROR_PORT_ORDER_INVALID = "结束端口不能小于起始端口"
)
