// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package node

import "flux-panel-go/internal/model/localErr"

const (
	// 节点默认状态：启用
	NodeStatusActive = 0

	// 成功响应消息
	SuccessCreateMsg = "节点创建成功"
	SuccessUpdateMsg = "节点更新成功"
	SuccessDeleteMsg = "节点删除成功"

	// 错误响应消息
	ErrorCreateMsg    = "节点创建失败"
	ErrorUpdateMsg    = "节点更新失败"
	ErrorDeleteMsg    = "节点删除失败"
	ErrorNodeNotFound = "节点不存在"

	// 隧道使用检查相关消息
	ErrorInNodeInUse  = "该节点还有 %d 个隧道作为入口节点在使用，请先删除相关隧道"
	ErrorOutNodeInUse = "该节点还有 %d 个隧道作为出口节点在使用，请先删除相关隧道"

	// 端口范围验证相关消息
	ErrorPortStaRequired  = "起始端口不能为空"
	ErrorPortEndRequired  = "结束端口不能为空"
	ErrorPortRangeInvalid = "端口必须在1-65535范围内"
	ErrorPortOrderInvalid = "结束端口不能小于起始端口"

	// 安装命令相关消息
	ErrorViteIpConfig = "请先前往网站配置中设置ip"
)

func validatePortRange(portStart, portEnd int) error {
	if portStart < 1 || portStart > 65535 || portEnd < 1 || portEnd > 65535 {
		return &localErr.CommonError{
			Code:   -2,
			ErrMsg: ErrorPortRangeInvalid,
		}
	}
	if portEnd < portStart {
		return &localErr.CommonError{
			Code:   -2,
			ErrMsg: ErrorPortOrderInvalid,
		}
	}
	return nil
}
