// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import "flux-panel-go/internal/model/entity"

const (
	ErrorLoginCredentials = "账号或密码错误"
	UserStatusActive      = 1
	UserStatusDisabled    = 0
	ErrorAccountDisabled  = "账号已被禁用"
	DefaultUsername       = "admin_user"
	DefaultPassword       = "admin_user"
	ErrorUsernameExists   = "用户名已存在"
	ErrorUsernameTaken    = "用户名已被其他用户使用"
	UserRoleId            = 1 // 普通用户角色ID
	ErrorCreateFailed     = "用户创建失败"
	SuccessCreateMsg      = "用户创建成功"
)

type LoginValidationResult struct {
	HasError     bool
	ErrorMessage string
	User         *entity.User
}
