// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"flux-panel-go/internal/dao/internal"
)

// forwardDao is the data access object for the table forward.
// You can define custom methods on it to extend its functionality as needed.
type forwardDao struct {
	*internal.ForwardDao
}

var (
	// Forward is a globally accessible object for table forward operations.
	Forward = forwardDao{internal.NewForwardDao()}
)

// Add your custom methods and functionality below.
