// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// nodeDao is the data access object for the table node.
// You can define custom methods on it to extend its functionality as needed.
type nodeDao struct {
	*internal.NodeDao
}

var (
	// Node is a globally accessible object for table node operations.
	Node = nodeDao{internal.NewNodeDao()}
)

// Add your custom methods and functionality below.
