// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"flux-panel-go/internal/dao/internal"
)

// speedLimitDao is the data access object for the table speed_limit.
// You can define custom methods on it to extend its functionality as needed.
type speedLimitDao struct {
	*internal.SpeedLimitDao
}

var (
	// SpeedLimit is a globally accessible object for table speed_limit operations.
	SpeedLimit = speedLimitDao{internal.NewSpeedLimitDao()}
)

// Add your custom methods and functionality below.
