// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"flux-panel-go/internal/dao/internal"
)

// statisticsFlowDao is the data access object for the table statistics_flow.
// You can define custom methods on it to extend its functionality as needed.
type statisticsFlowDao struct {
	*internal.StatisticsFlowDao
}

var (
	// StatisticsFlow is a globally accessible object for table statistics_flow operations.
	StatisticsFlow = statisticsFlowDao{internal.NewStatisticsFlowDao()}
)

// Add your custom methods and functionality below.
