// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"flux-panel-go/internal/dao/internal"
)

// tunnelDao is the data access object for the table tunnel.
// You can define custom methods on it to extend its functionality as needed.
type tunnelDao struct {
	*internal.TunnelDao
}

var (
	// Tunnel is a globally accessible object for table tunnel operations.
	Tunnel = tunnelDao{internal.NewTunnelDao()}
)

// Add your custom methods and functionality below.
