// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"flux-panel-go/internal/dao/internal"
)

// viteConfigDao is the data access object for the table vite_config.
// You can define custom methods on it to extend its functionality as needed.
type viteConfigDao struct {
	*internal.ViteConfigDao
}

var (
	// ViteConfig is a globally accessible object for table vite_config operations.
	ViteConfig = viteConfigDao{internal.NewViteConfigDao()}
)

// Add your custom methods and functionality below.
