// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package viteConfig

const ERROR_GET_VITE_CONFIGS_FAILED = "获取网站配置失败"
