// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package viteConfig

const ErrorGetViteConfigsFailed = "获取网站配置失败"
const ErrorConfigNotFound = "网站配置不存在"
